name: CI/CD Pipeline

on:
  push:
    branches:
      - pipeline  # Gantilah dengan branch yang sesuai jika perlu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Ganti dengan versi PHP yang kamu butuhkan

      - name: Install PHP extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y php-xml php-xmlwriter php-dom  # Install PHP extensions yang diperlukan

      - name: Install dependencies
        run: |
          composer install

      - name: Run Tests
        run: |
          php vendor/bin/phpunit  # Sesuaikan dengan perintah tes yang digunakan

      - name: Security Scan with SonarQube
        run: |
          # Jalankan perintah untuk memeriksa keamanan, contoh menggunakan SonarQube
          sonar-scanner

      - name: Deploy to Staging
        run: |
          # Perintah untuk deployment ke environment staging
          echo "Deploying to staging"

