name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: |
        composer install

    - name: Run Unit Tests
      run: |
        vendor/bin/phpunit

    - name: Security Scan
      run: |
        composer require --dev phpstan/phpstan
        vendor/bin/phpstan analyse src/ --level=max

    - name: Deploy to Staging
      run: |
        echo "Deployment script here (Docker, SCP, rsync, etc.)"

